[tox]
skipsdist = True

[testenv]
passenv = *
setenv =
    ARG_FILE={envtmpdir}/argument_file.txt
    OPENBMC_PASSWORD=0penBmc
    OPENBMC_USERNAME=root
    SYSLOG_IP_ADDRESS=127.0.0.1
    SYSLOG_PORT=514
    IPMI_COMMAND=External
    IPMI_CIPHER_LEVEL=17
allowlist_externals = *
install_command = pip install {opts} {packages}
deps = -r{toxinidir}/requirements.txt
commands =
    -mkdir -p {envtmpdir}
    bash {toxinidir}/tools/generate_argumentfile.sh
    cp bin/ssh_pw {envdir}/bin/ssh_pw


[testenv:default]
deps = {[testenv]deps}
setenv = {[testenv]setenv}
commands =
    {[testenv]commands}
    python3 -m robot.run --argumentfile {env:ARG_FILE} {posargs}


[testenv:palmetto]
deps     = {[testenv]deps}
setenv   = {[testenv]setenv}
    OPENBMC_MODEL=./data/Palmetto.py
commands =
    {[testenv]commands}
    python3 -m robot.run --argumentfile {env:ARG_FILE} {posargs}


[testenv:qemu]
deps     = {[testenv]deps}
setenv   = {[testenv]setenv}
    OPENBMC_MODEL=./data/Palmetto.py
commands =
    {[testenv]commands}
    python3 -m robot.run --argumentfile {env:ARG_FILE} {posargs}


[testenv:witherspoon]
deps     = {[testenv]deps}
setenv   = {[testenv]setenv}
    OPENBMC_MODEL=./data/Witherspoon.py
commands =
    {[testenv]commands}
    python3 -m robot.run --argumentfile {env:ARG_FILE} {posargs}

[testenv:romulus]
deps     = {[testenv]deps}
setenv   = {[testenv]setenv}
    OPENBMC_MODEL=./data/Romulus.py
commands =
    {[testenv]commands}
    python3 -m robot.run --argumentfile {env:ARG_FILE} {posargs}

[testenv:e2ps23]
deps     = {[testenv]deps}
setenv   = {[testenv]setenv}
    OPENBMC_HOST=192.168.20.100
    HTTPS_PORT=443
    SSH_PORT=22
    IPMI_PORT=623
    LDAP_BASE_DN=dc=phytium,dc=com
    LDAP_BIND_DN=cn=admin,dc=phytium,dc=com
    LDAP_SERVER_URI=ldaps://192.168.20.103:636/
    LDAP_BIND_DN_PASSWORD=0penBmc
    LDAP_TYPE=LDAP
    LDAP_USER=test
    LDAP_USER_PASSWORD=123123
    GROUP_NAME=openbmc
    GROUP_PRIVILEGE=Administrator

commands =
    {[testenv]commands}
    python3 -m robot.run --argumentfile {env:ARG_FILE} {posargs}
